Repository DoctorGrim/YNAB-google-assistant, pull requests merged in 2019-08, with the labels that each got.

#1 YNAB API starter kit
  YNAB-starter-kit.js
  bin/start.js
  index.js
  package.json
Labels: good first issue

#28 Fetch budget with API token, no OAuth
  firebase.json
  functions/index.js
  functions/package-lock.json
  functions/package.json
  index.js
  package-lock.json
  package.json
Labels: enhancement

#47 minor dialogue and formatting fixes.
  .vscode/settings.json
  .vscode/spellright.dict
  functions/index.js
Labels: chore, help wanted

#51 wording made more like Alexa
  functions/index.js
Labels: chore, help wanted
